### ISSUE TITLE
Yabai todo

### ISSUE THREAD

**Issue by bookercodes** [bookercodes/macos-dots#1]
- [ ] One bind to resize floating _and_ tiled windows
- [ ] Bind to throw window to workspace N
- [ ] Modal binds to move floating windows (to left edge, centre, right edge)
